tree.heading("one", text="Ders 1")
tree.heading("two", text="Ders 2")
tree.heading("three", text="Ders 3")
tree.heading("four", text="Ders 4")
tree.heading("five", text="Ders 5")
tree.heading("six", text="Ders 6")
tree.heading("seven", text="Ders 7")
tree.heading("eight", text="Ders 8")

tree.insert("" , 1,    text="Pazartesi", values=("Kimya","Kimya","Türkçe","Türkçe","Matematik(Mikail)","Matematik(Mikail)","İngilizce(Feryat)","İngilizce(Feryat)"))
tree.insert("" , 2,    text="Salı", values=("Ders 1","Ders 2","Ders 3","Ders 4","Ders 5","Ders 6","Ders 7","Ders 8"))
tree.insert("" , 3,    text="Çarşamba", values=("Ders 1","Ders 2","Ders 3","Ders 4","Ders 5","Ders 6","Ders 7","Ders 8"))
tree.insert("" , 4,    text="Perşembe", values=("Ders 1","Ders 2","Ders 3","Ders 4","Ders 5","Ders 6","Ders 7","Ders 8"))
tree.insert("" , 5,    text="Cuma", values=("Ders 1","Ders 2","Ders 3","Ders 4","Ders 5","Ders 6","Ders 7","Ders 8"))
tree.insert("" , 6,    text="", values=(""))
tree.insert("" , 7,    text="Son güncellenme tarihi", values=("%s" % time.ctime(os.path.getmtime("data.py"))))
